option('fuzzing', type: 'boolean', value: false, description: 'Enable fuzzing tests')
option('lib_fuzzing_engine', type : 'string', value : '', description : 'Path to the libFuzzer engine library')
option('upf_memif', type : 'boolean', value : false, description : 'Build the UPF N6 libmemif backend')
