apiVersion: v1
kind: Service
metadata:
  name: {{ include "xcn.componentName" (dict "root" . "component" "mongodb-headless") }}
  labels:
    {{- include "xcn.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "xcn.componentName" (dict "root" . "component" "mongodb") }}
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xcn.componentName" (dict "root" . "component" "mongodb") }}
  labels:
    {{- include "xcn.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "xcn.componentName" (dict "root" . "component" "mongodb") }}
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "xcn.componentName" (dict "root" . "component" "mongodb") }}
  labels:
    {{- include "xcn.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "xcn.componentName" (dict "root" . "component" "mongodb-headless") }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "xcn.componentName" (dict "root" . "component" "mongodb") }}
  template:
    metadata:
      labels:
        app: {{ include "xcn.componentName" (dict "root" . "component" "mongodb") }}
    spec:
      containers:
        - name: mongodb
          image: {{ printf "%s:%s" .Values.images.mongodb.repository .Values.images.mongodb.tag }}
          imagePullPolicy: {{ .Values.images.mongodb.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: mongodb
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            tcpSocket:
              port: mongodb
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: mongodb
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources.mongodb.mongodb | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data/db
{{- include "xcn.localtimeVolumeMount" . | nindent 12 }}
      volumes:
{{- if not .Values.mongodb.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- end }}
        - name: mongo-init
          configMap:
            name: {{ include "xcn.componentName" (dict "root" . "component" "mongo-init") }}
{{- include "xcn.localtimeVolume" . | nindent 8 }}
{{- if .Values.mongodb.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
{{- if .Values.mongodb.persistence.storageClassName }}
        storageClassName: {{ .Values.mongodb.persistence.storageClassName | quote }}
{{- end }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
{{- end }}
